const destinyData = {
    1: `According to Chaldean numerology, your Destiny/Expression number is 1. The Sun rules the number 1. The 1 means Leader, Independent, Creative.
    You are influenced by the qualities of planet Sun, like firmly determined, brave, and leadership qualities. You are an original thinker and originator of all actions. You have the quality to control everything around you. Sometimes, you become stubborn and angry when things do not happen according to your desires. You are a real and original thinker, creative, and dominant person. You may play a good role as an inventor, leader, explorer, and head of the family. Number one represents the card Magician – The Purpose.`,
    2:`According to Chaldean numerology, your Destiny/Expression number is 2. The Moon rules the number 2. The 2 means Diplomat, Peacemaker, Sensitive.
    You are ruled and influenced by the planet Moon. Number 2 represents sensitivity, imagination and dream oriented nature. You are such a romantic and co-operative person that people want to live with you as people know you as a real peacemaker. You are a diplomat person of a dual personality. You are fond of music and may become a good singer. You love traveling and you love your home too. Many times, you have unknown fears in your life, so you adopt secretive behavior and hence people cannot judge your next move. The more energy of number two may make you shy, oversensitive and makes you a fantasy dreamer. The number two represents the card High Priestess – The Feminine.`,
    3:`According to Chaldean numerology, your Destiny/Expression number is 3. Jupiter rules the number 3. The 3 means Creative, Entertainer, Ideal.
    You have the qualities of the planet Jupiter and you are influenced by Jupiter in your whole life. The person of number 3 is a social person who is creative, communicative and dramatic. The number 3 represents artistic talents, charismatic personality and cheerful behavior. You are a religious, truthful, highly educated or highly skilled person. You may become a great ideal for others. You love to travel and learn the new ways of joy and happiness. You trust in total freedom in every aspect of life, especially freedom of speech. You can become a good lawyer, artist, writer or publisher. Number three represents the card Empress – The Activity.`,
    4:`According to Chaldean numerology, your Destiny/Expression number is 4. The Uranus or Rahu rule the number 4. The 4 means Secretive, Dependable, Practical.
    The Uranus or Rahu is known for the sudden and unexpected events in mysterious ways. The Uranus or Rahu influences you in your life. You face many unexpected events in life due to this. You are a practical person who believes in individualism, tolerance and originality. Secretive nature and unexpected behavior towards others are the main traits of number four. You always plan to make the foundation of the future with weird ideas. You are a systematic and trustworthy person. You have a long list of likes and dislikes, you should avoid stubbornness and rigid behavior towards others. Number four represents the card Emperor – The Overcoming.`,
    5:`According to Chaldean numerology, your Destiny/Expression number is 5. Mercury rules the number 5. The 5 means Communicator, Restless, Versatile.
    You have the traits of the planet Mercury such as fast movement, versatile nature, communication skill and multi-talents. These qualities give you the opportunity to become a good salesperson, actor, writer, media and commercial post related to sales and communication. You are clever and can make quick responses or ideas for any problem. You love freedom, adventure, and work with high risk. Some of the people of number five are highly workaholic and restless, due to this, they may suffer from nerve related problems. Due to analytical nature, you disappoint the people who are close to you. Number five represents the card Hierophant – The Voice.`,
    6:`According to Chaldean numerology, your Destiny/Expression number is 6. Venus rules the number 6. The 6 means Healer, Teacher, Counselor.
    You are influenced by Venus, the planet of love, romance, beauty, art, and truth. So, you are a loving person with a romantic image. You strongly trust in truth, justice, and humanity. You are a born teacher and healer, who is always ready to help others with counseling skills. The person of number six is a divine lover and always stands for family and friends. You love luxury and harmony in life. Number six persons may become good singers, counselors, teachers, and they are good at art related works. Number six represents the card Lovers – The Path`,
    7:`According to Chaldean numerology, your Destiny/Expression number is 7. Neptune or Ketu rules the number 7. The 7 means Spiritual, Investigator, Seeker. You are under the influence of Neptune or Ketu planet. This planet represents spirituality, philosophy and mystery. You always search for answers to questions, which you face in your life journey. The number 7 forces you to make illusions and delusions. You have a mysterious nature, you do dream a lot more than others. You always investigate the reason for the happenings. You often feel you are a gifted person with clairvoyance and intuition powers. You are an introverted person and often do not share your feelings and problems with others. The number seven represents the card Chariot – The Victory.`,
    8: `According to Chaldean numerology, your Destiny/Expression number is 8. Saturn rules the number 8. The 8 means Game changer, Money maker, Manager.
    You are under the influence of the planet Saturn. This planet represents stability, true judgment and great responsibility. You have the born qualities to manage financial things and politics, indeed, the person with number eight may become a great business person or a leader and a game changer in the finance or politics world. You have good self-control and determination, with reserved nature. You can balance everything in life and between situations. The number eight represents the card Justice – The Balance.`,
    9:`According to Chaldean numerology, your Destiny/Expression number is 9. Mars rule number 9. The 9 means Courageous, Humanitarian, Aggressive.
    You are influenced by the qualities of planet Mars. You are an aggressive person, who is not afraid to take risks, a courageous person with the traits of humanity and kindness. You are always ready to help others when they need you. You get everything, what you are determined to get by taking any level of risk. You trust everyone and are often defeated by hidden enemies, although you cannot be defeated, if you know your enemies. Anger and impatience is a bad part of your nature. Number nine represents the card Hermit – The Light.`,
    11:`According to Chaldean numerology, your Destiny/Expression number is 11. The Moon rules the number 11/2. The 11/2 means Highly sensitive, Spiritual, Secretive.
    The number 11 is a master number, and 2 stands for a single number. Both are ruled by the planet Moon. Because this number is called the master number, it means you have double and special powers with this number. It represents high sensitivity, spiritual and high imagination powers. You may become an intuitive and psychic person. Because of the Moon, you are very soft towards others and you blindly trust others, and in result, you often get treachery and hidden dangers from others. You have a very secretive nature and hence people cannot understand you easily. Number eleven represents the card Lion Muzzled.`,
    22:`According to Chaldean numerology, your Destiny/Expression number is 22. The Uranus or Rahu rules the number 22/4. The 22/4 means Dreamer, Systematic, Illusionist.
    The 22 is called the master number, the 4 is a single number, and both are influenced by Uranus/Rahu. Due to the planet's traits, you live in dreams. You have your own world of illusion, and are often awake after falling into danger. Unexpected events are the main traits of number 22, due to this you may face hidden enemies and hidden dangers which are always around you in your whole life. Although, the master number gives you more powers, like you are very trustworthy, a good manager, energetic, capable and systematic. You always plan for the future, but you should be cautious about future events because of your illusion nature.`,
    33:`According to Chaldean numerology, your Destiny/Expression number is 33. Venus rules the number 33/6. The 33/6 means Healer, Teacher, Counselor.
    The 33 is known as the master number and the 6 is a single digit number, and both are ruled and influenced by the planet Venus. Due to the double power of the master number this is a fortunate digit. This is lucky for love matters, finance and money matters. You are a true and charming lover for your partner. You are overconfident, but a skilled and highly creative person too. Amazing teachers, counselors and healers are born with the 33 number.`
}

const soulData = {
    0:`It doesn't mean that you don't have an inner personality. In the absence of a Soul Urge number, your outer personality will be visible in your inner personality. Simply put, your dream number's traits will show up for the Soul Urge number.`,
    1:`According to the vowels in your name, Soul Urge number is 1. The 1 means Accomplisher and Desire for leadership. The number 1 is influenced by the Sun, the planet Sun gives you a deep desire to be the leader of family and others. You want respect and credit from the people surrounding you. You want and you can complete the work, as you are the best accomplishment person. You are a winner, when you are appreciated for what you are doing, because this fills you with lots of positivity and creativity.`,
    2: "According to the vowels in your name, Soul Urge number is 2. The 2 means Peacemaker and Desire for love. The number 2 is influenced by the Moon, which gives you the inner quality of peacemaking, a born friendly and cooperative nature. You want everything to be easy going in any situation. You need a deep inner desire for love, peace and harmony.",
    3:`According to the vowels in your name, Soul Urge number is 3. The 3 means Cheerful and Artistic desire. The Soul urge number three is influenced by Jupiter, so your inner desire reflects the traits of Jupiter such as artistic talents, charismatic personality and cheerful behavior. You tend to be joyful for yourself and others. You have a strong desire to express yourself in an artistic manner. You have an inner desire to be the leader in any group surrounding you.`,
    4:`According to the vowels in your name, Soul Urge number is 4. The 4 means Loyal and Desire for security. The heart desire number four is influenced by Uranus/Rahu, therefore your inner desire reflects the qualities of Uranus/Rahu. You have a strong desire to be safe for finance and the future. You always want respect for your loyalty and workmanship. Security and protection from everything is an inner need of you.`,
    5:`According to the vowels in your name, Soul Urge number is 5. The 5 means Learner and Desire for freedom. Mercury influences the Soul Urge number five, so you have the strong inner desire for freedom in every aspect of life. You have a deep curiosity to know, learn and execute any work. This number tends to be adventurous with new and unusual things. You want change, either at your home or your workplace.`,
    6:`According to the vowels in your name, Soul Urge number is 6. The 6 means Responsible and Desire for luxury. Venus influences the heart desire number 6, therefore you want to be an ideal person in the family. You have a deep affection and a sense of responsibility for your spouse and family. You are a good healer, nurturer and want to do more for people you love a lot. You have a desire for love, luxury life, and harmony.`,
    7:`According to the vowels in your name, Soul Urge number is 7. The 7 means Intellectual and Desire for learning. The Soul Urge number 7 is influenced by Neptune/Ketu, therefore you have the great need to know and learn spiritual aspects. You have the desire to spend life with peace and comfort. You want to learn everything. You have a deep desire to obtain more wisdom to be a perfectionist and intellectual.`,
    8:`According to the vowels in your name, Soul Urge number is 8. The 8 means Dependable and Desire for authority. Saturn influences this heart desire number 8, so you have a deep heart's desire to be the leader in a workplace or in a business. You want to secure the future and success in a financial manner. You want to be a powerful person with authority. In simple words, you need to be rich and a big boss in commercial projects.`,
    9:`According to the vowels in your name, Soul Urge number is 9. The 9 means Knowledgeable and Desire of humanity. Mars influences the Soul Urge number nine, therefore, you have a deep desire to serve humanity and the world with your knowledge and experiences without expecting anything. You tend to be a courageous person for taking risks.`,
    11:`According to the vowels in your name, Soul Urge number is 11. The 11/2 means Dreamer and Desire for spirituality. The Heart Desire number 11 is known as the master number with traits of number 2, which is influenced by the Moon. Therefore, you have a strong desire to be a spiritual, peace maker and psychic person. You are a dreamer and want that the dreams should come true in your way.`,
    22:`According to the vowels in your name, Soul Urge number is 22. The 22/4 means Realistic and Desire for a safe future. The Soul Urge number 22 is known as the master number with traits of number 4, which is influenced by the Uranus/Rahu. Therefore, you have a strong desire for a safe and secure future. You want respect and love from family and friends. You tend to be a powerful person and realistic. You want to be an ambitious and confident persona and builder of the future.`,
    33:`According to the vowels in your name, Soul Urge number is 33. The 33/6 means Responsible and Desire for luxury. The Heart Desire number 33 is known as the master number with traits of number 6, which is influenced by Venus. Therefore, you have a deep desire for luxury and love from family. You want to secure your family in a financial and health manner. You tend to be responsible for family and the work.`

}




module.exports = {destinyData, soulData} ;